---
layout: essay
type: essay
title: "Our home in the sky: Indigenous erasure in Hawaii"
# All dates must be YYYY-MM-DD format!
date: 2022-07-15
published: true
labels:
  - Ethnic studies
  - Astronomy
---

  When astronomers say there is no better place in the world to study the stars than on the summit of Mauna Kea, they aren’t lying. At 4200m above sea level, Mauna Kea experiences low light pollution and air disturbances. This creates an ideal environment for space observation. Mauna Kea has a sacred place in Hawaiian culture as the home of Poliahu. Historical trails, heiau, and burial sites being overrun by construction sites for defunct telescopes are reminders of Hawaii’s colonization. Ignored by the government and scorned by the local astronomy community, the treatment of Kānaka Maoli and Maunakea perpetuates a long history of Indigenous erasure in science.
  Exclusivity and the search for objectivity in science is not a new development. From the Protestant Reformation in the 16th century came the philosophers’ desire to separate their ideas from religious influence. However, they did not realize that the same principles of thought once applied externally by a priest were now being applied internally under the guise of a “common sense.” (Foster, 1934, p. 450). Though this was later criticized, works from these “emancipated” thinkers had already set the frame for what was to be considered objective thinking. A method of natural sciences based upon “the doctrine of God” was widely accepted, and as European influence (as well as Eurocentrism) spread, became dominant and viewed as objective in studies of nature. Hawaiian geological history has long been passed down through mo’olelo, which often detail changes in nature. Yet, they are often discarded by scientists as mere storytelling. Peter Keali’i Thoene discusses the internal conflict he felt being a Native Hawaiian naturalist, in a scientific world that rejected mo’olelo. He gives several examples of mo’olelo revealing important details about Kīlauea, finding that the “geological timeline and chain of events matched the mo’olelo (Holo Mai Pele) (pp. 7). In addition, a mo’olelo about He’eia fishpond revealed a “complex understanding of not only the pond’s biological processes” and “responsible ecosystem management,” referring to the nitrogen cycle keeping the pond balanced. Western science and mo’olelo accomplish the same goal of helping people understand the Earth and its processes.
	Though the origin of “objective” science dates back to many centuries ago, academics today are still struggling with attempts to decolonize science– not only in including more diverse topics, but also in questioning what is considered to be science. In social sciences, Sociology professor Syed Farid Alatas (2002) notes that despite Asian, African, and Latin communities advocating to “decolonize knowledge,” independent academic traditions were not established, nor were they promoted in curriculums (p. 766). While names like Ibn Kaldun, Raja Ram Mohan Moy, José Rizal, and Benoy Kumar Sarkar are glossed over outside of Alatas’ classroom, Marx, Weber, and Durkheim continued to be emphasized, creating a focus on European ideas. In math, one of the only subjects taught without historical or cultural background, historical feats go undiscussed and the mathematical achievements of non-Europeans like Srinivasa Ramanujan are unnoticed. Black educator and activist S. E. Anderson (1990) states that “European names such as Pythagoras, Euclid, Cauchy-Rieman, Fourier, and Newton are tossed about… and attached to various levels of abstractions as if they always existed.” (p. 351). This ahistoric form of teaching excludes significant feats accomplished by mathematicians elsewhere and promotes a Eurocentric view of the world.
	It is not unfathomable to predict the effects that these issues have had on our perception of science today. It is well-known that Native Hawaiians practice astronomy for its usefulness in navigation and to predict crop seasons, as well as astrology to make predictions for the future. Twentieth-century astronomer Maud Makemson (1939) observed that these astrologers were “regular in their observations every morning” and that they had detailed knowledge of star patterns and movements (p. 593-594). Kānaka Maoli have forms of astronomy significant to them, yet Western astronomy has taken itself to be more valuable. Anthropology professor Iokepa Casumbal-Salazar (2017) asserts that “Native culture, language, and histories are valued only insofar as they affirm the settler state’s commitment to capital and authority to govern” and that the government operates on an inherent contradiction between “its commitment to both capitalism and Kānaka ‘Oiwi.” (p. 12). Protesters of the infamous Thirty Meter Telescope construction took to displays of Hawaiian culture as a form of resistance, and in doing so were “rendered selfish, aggressive, and unreasonable… as the agnostic menace of the modern scientific state.” (p. 2). In a world where Western is conflated with modern, Kānaka Maoli are superficially lauded as relics of tradition while their voices are ignored.
	The world of science, often seen as objective, has its roots in religious influence and continues to be taught and practiced under European influence. Activists continue to work towards decolonizing and redefining science. The treatment of Kānaka Maoli and erasure of the cultural significance of Mauna Kea is just one of the ways this presents itself in Hawaii. In order to unlearn the biases instilled through science, it is necessary to expand its sources to include Indigenous ideas.

**References**

Alatas, S. F. (2002). Eurocentrism and the Role of the Human Sciences in the Dialogue among Civilizations. The European Legacy, 7(6), 759-770. https://doi.org/10.1080/1084877022000029046
Anderson, S.E. (1990). Worldmath Curriculum: Fighting Eurocentrism in Mathematics. The Journal of Negro Education, 59(3), 348-359. https://doi.org/10.2307/2295569
Casumbal-Salazar, I. (2017). A Fictive Kinship: Making “Modernity,” “Ancient Hawaiians,” and the Telescopes on Mauna Kea. Native American and Indigenous Studies, 4(2), 1-30. https://doi.org/10.5749/natiindistudj.4.2.0001
Foster, M. B. (1934). The Christian Doctrine of Creation and the Rise of Modern Natural Science. Mind, 43(172), 446-468. 
Makemson, M. W. (1939). Hawaiian Astronomical Concepts II. American Anthropologist, 41(4), 589-596.
Thoene, P. K. (n. d.). Excavating the Scientific Truths in Hawaiian Mo‘olelo. Flux. https://fluxhawaii.com/the-science-behind-hawaiian-myths/


